apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-producao
spec:
  # ATENÇÃO: A linha "replicas" foi deletada de propósito!
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: app
        image: registry.k8s.io/hpa-example
        resources:
          requests:
            cpu: 100m
            memory: 128Mi