apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      values: |
        grafana:
          enabled: true
          image:
            tag: latest
        loki:
          enabled: true
          persistence:
            enabled: false
        promtail:
          enabled: true
          config:
            lokiAddress: http://grafana-loki:3100/loki/api/v1/push
            snippets:
              extraScrapeConfigs: |
                - job_name: system_logs
                  static_configs:
                  - targets:
                      - localhost
                    labels:
                      job: varlogs
                      __path__: /var/log/*log
          extraVolumes:
            - name: host-logs
              hostPath:
                path: /var/log
          extraVolumeMounts:
            - name: host-logs
              mountPath: /var/log
              readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true